version: "3.8"
services:
    backend:
        build:
            context: ./bcpsbackend
            dockerfile: Dockerfile
        ports:
            - 3000:8000
        volumes:
            - ./bcpsbackend:/app/bcpsbackend
        networks:
            - app

    frontend:
        build:
            context: ./bcpsfrontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - 8080:3000
        volumes:
            - ./bcpsfrontend:/app/bcpsfrontend
            - /app/bcpsfrontend/node_modules
        depends_on:
            - backend
        networks:
            - app

networks:
    app:
        driver: bridge
